TEFMvcDemo/Models/ScopingIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TEFMvcDemo.Models
{
   public class ScopingIndexModel
   {

      public string PerRequestTime { get; set; }

      public string GlobalTime { get; set; }


   }
}

TEFMvcDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TEFMvcDemo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
          
            return View();
        }
    }
}

TEFMvcDemo/Controllers/SampleInjectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using TEFMvcDemo;


namespace TEFMvcDemo.Controllers
{
    public class SampleInjectionController : Controller
    {
      private TEFMvcDemo.ICacheService _cacheService = null;
      private TEFMvcDemo.ISessionService _sessionService = null;
      //List support for one-to-many is supported; how you consume the references may vary by container
      private IList<TEFMvcDemo.IStateOptionsService> _stateService = null;



      /// <summary>
      /// The container is doing all the work here; this is to demo that TEF did correctly import the singletons and lists of mappings.
      /// </summary>
      /// <param name="cacheService"></param>
      /// <param name="sessionService"></param>
      /// <param name="stateService"></param>
      public SampleInjectionController(ICacheService cacheService, ISessionService sessionService, IList<TEFMvcDemo.IStateOptionsService> stateService)
      {
         _cacheService = cacheService;
         _sessionService = sessionService;
         _stateService = stateService;
      }




        public ActionResult Index()
        {
            
            return View();
        }

    }
}

TEFMvcDemo/Controllers/ScopingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TEFMvcDemo;


namespace TEFMvcDemo.Controllers
{
    public class ScopingController : Controller
    {
      private IRequestTimeService _rqTime = null;
      private ISingletonTimeService _singletonTime = null;


      /// <summary>
      /// Since these two objects are scoped differently, you'll see a disparity in the time reported; since the time is stored
      /// in a variable defined in the constructor, the singleton's constructor is only called once, where the per request service
      /// recreates every ASP.NET request.
      /// </summary>
      /// <param name="rqTime">The per request service to report time - updates every time.</param>
      /// <param name="singTime">The singleton service to report time - only reports one time.</param>

      public ScopingController(IRequestTimeService rqTime, ISingletonTimeService singTime)
      {
         _rqTime = rqTime;
         _singletonTime = singTime;
      }



        public ActionResult Index()
        {
            var model = new Models.ScopingIndexModel();
            model.PerRequestTime = _rqTime.GetTime();
            model.GlobalTime = _singletonTime.GetTime();

            return View(model);
        }
    }
}

TEFMvcDemo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
       This site is customized in a few ways.  See the DependencyInjectionConfig.cs class in App_Start folder; This is called from Global.asax.
       I separate the DI setup process from the other App_Start components so it stands out, but of course, you don't need to follow that
       convention.
    </p>
   <p>
      See the examples linked on the home page to view some of the demos.  This framework is useful, but not necessary helpful as a demo scenario,
      but more of an example scenario.  See the sample implementations in TEFMvcDemo.Classes project to illustrate how the ExportType and
      ExportAssembly attributes are used.
   </p>
</article>

TEFMvcDemo/Views/Home/Index.cshtml
@using System.Web.Mvc;
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>TEF DEMO</h1>
                <h2>The following is a simple demo of TEF.</h2>
            </hgroup>
            <p>
                Check out the App_Start folder, for the DependencyInjectionConfig project.  In here,
				we have some code that uses TEF to inspect the attached assemblies.  Assemblies can
				be inspected at an assembly level, a type collection level, or AppDomain level.
				To register a type, apply an [ExportType] attribute to a class, or [assembly:ExportDependency]
				within the class file at the class's header.
            </p>
        </div>
    </section>
}

<div class="well">
   <h3>The following sample demonstrations:</h3>
   <ul>
      <li>
         <a href="@Url.Action("Index", "Scoping")">Scoping Demo</a>
      </li>
      <li>
         <a href="@Url.Action("Index", "SampleInjection")">Sample Injections - Put a breakpoint in controller to view.</a>
      </li>
   </ul>
</div>

<div class="well">
	<h3>The following types are registered:</h3>
	@{
		var container = (DependencyResolver.Current as SimpleInjector.Integration.Web.Mvc.SimpleInjectorDependencyResolver).Container;
		var registrations = container.GetCurrentRegistrations();

		foreach (var reg in registrations)
		{
			<div>
				<span>@reg.ServiceType.Name = @reg.Registration.ImplementationType.Name</span>
			</div>
		}
	}
</div>

TEFMvcDemo/Views/SampleInjection/Index.cshtml
@{
    ViewBag.Title = "Sample Injections";
}

<p>
   Put a breakpoint in the controller to view dynamic constructor injection.
</p>

TEFMvcDemo/Views/Scoping/Index.cshtml
@model TEFMvcDemo.Models.ScopingIndexModel
@{
    ViewBag.Title = "Index";
}

<div>
   Time from Per Request Service:
</div>

<div>
   @Model.PerRequestTime
</div>

<div>
   Time from Singleton Service:
</div>

<div>
   @Model.GlobalTime
</div>

<div>

   <a href="@Url.Action()">Refresh</a>

</div>

TEFMvcDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - TEF Demo MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>